name: Build
on: [push]
jobs:
  nvda:
    runs-on: macos-latest
    steps:
      - name: Set up Windows
        run: |
          vagrant init assistive-webdriver/win10-chromium-nvda
          vagrant up
          vagrant provision --provision-with start-assistive-playwright
          vboxwebsrv --authentication null
