name: Build
on: [push]
jobs:
  nvda:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Set up Windows
        run: |
          vagrant init assistive-webdriver/win10-chromium-nvda
          vagrant up
      - name: Provision Assistive Playwright
        run: |
          vagrant provision --provision-with start-assistive-playwright
          vboxwebsrv --authentication null &
      - name: Run tests
        run: |
          npx @playwright/test test
