name: Build
on: [push]
jobs:
  nvda:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: guidepup/setup-action
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install browsers
        run: |
          yarn install
          npx playwright install --with-deps chromium
      - name: Run tests
        run: |
          npx playwright test
